[dog]
name = "dog"
ch = "d"
color = "desaturatedGreen"
[dog.destructible]
maxHp = 2
defense = 0
xp = 25
corpseName = "dead dog"
[dog.attacker]
numberOfDice = 1
dice = 2
bonus = 1
[dog.ai]
type = "MonsterAi"
speed = 200
[dog.body] # empty table = default body

[snake]
name = "snake"
ch = "s"
color = "desaturatedGreen"
[snake.destructible]
maxHp = 2
defense = 0
xp = 50
corpseName = "dead snake"
[snake.attacker]
numberOfDice = 2
dice = 2
bonus = 0
[snake.ai]
type = "MonsterAi"
speed = 100
[snake.container]
capacity = 2
contents = [ { with_probability = 66, content = "snakemeat"} ] # with_probability is optional
[snake.body] # empty table = default body
