[dog]
name = "dog"
ch = "d"
color = "desaturatedGreen"
[dog.destructible]
maxHp = 2
defense = 0
xp = 25
corpseName = "dead dog"
[dog.attacker]
numberOfDice = 1
dice = 2
bonus = 1
[dog.ai]
type = "MonsterAi"
speed = 200
[dog.body] # empty table = default body

[snake]
name = "snake"
ch = "s"
color = "desaturatedGreen"
[snake.destructible]
maxHp = 2
defense = 0
xp = 50
corpseName = "dead snake"
[snake.attacker]
numberOfDice = 2
dice = 2
bonus = 0
[snake.ai]
type = "MonsterAi"
speed = 100
[snake.container]
capacity = 1
contents = [ { with_probability = 66, content = "snakemeat" } ] # with_probability is optional
[snake.body] # empty table = default body

[child]
name = "child"
ch = "c"
color = "desaturatedGreen"
[child.destructible]
maxHp = 2
defense = 0
xp = 25
corpseName = "dead child"
[child.attacker]
numberOfDice = 1
dice = 2
bonus = 0
[child.ai]
type = "MonsterAi"
speed = 75
[child.container]
capacity = 10
contents = [ { with_probability = 66, content = "super_stimpak" },
             { with_probability = 66, content = "snakemeat" } ]
[child.body]

[punk]
name = "punk"
ch = "h"
color = "desaturatedGreen"
[punk.destructible]
maxHp = 3
defense = 0
xp = 50
corpseName = "dead punk"
[punk.attacker]
numberOfDice = 1
dice = 3
bonus = 0
[punk.ai]
type = "MonsterAi"
speed = 100
[punk.container]
capacity = 10
contents = [ { content = "cookie" } ]
[punk.body]

[guard]
name = "guard"
ch = "h"
color = "darkGreen"
[guard.destructible]
maxHp = 6
defense = 1
xp = 100
corpseName = "guard body"
[guard.attacker]
numberOfDice = 1
dice = 3
bonus = 0
[guard.ai]
type = "MonsterAi"
speed = 200
[guard.container]
capacity = 10
contents = [ { content = "ration" },
             { with_probability = 66, content = "stimpak" } ]
[guard.body]
