# Comestibles

[snakemeat]
name = "snakemeat"
ch = "%"
color = "darkerYellow"
blocks = false
[snakemeat.pickable]
[snakemeat.comestible]
nutrition = 5000

[cookie]
name = "cookie"
ch = "%"
color = "darkerYellow"
blocks = false
[cookie.pickable]
[cookie.comestible]
nutrition = 10000

[ration]
name = "ration"
ch = "%"
color = "darkerGreen"
blocks = false
[ration.pickable]
[ration.comestible]
nutrition = 30000

# Syringes

[stimpak]
name = "stimpak"
ch = "!"
color = "grey"
blocks = false
[stimpak.pickable]
targetSelector.type = "Wearer"
targetSelector.range = 0
effect.type = "HealthEffect"
effect.value = 4

[super_stimpak]
name = "super stimpak"
ch = "!"
color = "grey"
blocks = false
[super_stimpak.pickable]
targetSelector.type = "Wearer"
targetSelector.range = 0
effect.type = "HealthEffect"
effect.value = 8

# Weapons

[knuckleduster]
name = "knuckle duster"
ch = "|"
color = "lightGreen"
blocks = false
[knuckleduster.pickable]
[knuckleduster.attacker]
numberOfDice = 2
dice = 6
bonus = 2
effect = "MoveEffect"
[knuckleduster.wieldable]
type = "OneHand"
