[1]
mapType = "Building"
being_probability = 0.003 # per tile
item_probability = 0.05 # per tile
beings = [ { amount = 1, being = "fighter" },
           { amount = 1, being = "bill" },
           { with_weight = 5, being = "dog" },
           { with_weight = 1, being = "snake" },
           { with_weight = 3, being = "child" },
           { with_weight = 1, being = "punk" } ]
items = [ { amount = 1, item = "phlebotinum_link" },
          { with_weight = 1, item = "jerky" },
          { with_weight = 1, item = "iodine_syringe" },
          { with_weight = 1, item = "stimpak" },
          { with_weight = 1, item = "fake_stimpak" },
          { with_weight = 1, item = "antidote" },
          { with_weight = 1, item = "blaster_bolt_device" },
          { with_weight = 1, item = "frag_grenade" },
          { with_weight = 1, item = "confusor" },
          { with_weight = 1, item = "tesla_coil" },
          { with_weight = 1, item = "rock" },
          { with_weight = 1, item = "baton" },
          { with_weight = 1, item = "knuckleduster" },
          { with_weight = 1, item = "pistol" },
          { with_weight = 1, item = "rifle" },
          { with_weight = 1, item = "leather_armor" },
          { with_weight = 1, item = "combat_armor" },
          { with_weight = 1, item = "flat_cap" },
          { with_weight = 1, item = "combat_helmet" },
          { with_weight = 1, item = "combat_boots" },
          { with_weight = 1, item = "navcomp" } ]

[2]
mapType = "Water"
being_probability = 0.003
item_probability = 0.01
beings = [ { with_weight = 4, being = "snake" },
           { with_weight = 2, being = "child" },
           { with_weight = 1, being = "guard" },
           { with_weight = 1, being = "boxer" },
           { with_weight = 2, being = "punk" } ]
items = [ { amount = 1, item = "phlebotinum_link" },
          { with_weight = 1, item = "jerky" },
          { with_weight = 1, item = "iodine_syringe" },
          { with_weight = 1, item = "stimpak" },
          { with_weight = 1, item = "fake_stimpak" },
          { with_weight = 1, item = "antidote" },
          { with_weight = 1, item = "blaster_bolt_device" },
          { with_weight = 1, item = "frag_grenade" },
          { with_weight = 1, item = "confusor" },
          { with_weight = 1, item = "tesla_coil" },
          { with_weight = 1, item = "rock" },
          { with_weight = 1, item = "baton" },
          { with_weight = 1, item = "knuckleduster" },
          { with_weight = 1, item = "pistol" },
          { with_weight = 1, item = "rifle" },
          { with_weight = 1, item = "leather_armor" },
          { with_weight = 1, item = "combat_armor" },
          { with_weight = 1, item = "flat_cap" },
          { with_weight = 1, item = "combat_helmet" },
          { with_weight = 1, item = "combat_boots" },
          { with_weight = 1, item = "navcomp" } ]

[3]
mapType = "Hardcoded" # TODO implement
mapFile = "Doesn't exist yet" # TODO implement
being_probability = 0.003
item_probability = 0.01
beings = [ { with_weight = 3, being = "guard" },
           { with_weight = 2, being = "boxer" },
           { with_weight = 3, being = "mutant" },
           { with_weight = 2, being = "punk" } ]
items = [ { amount = 1, item = "phlebotinum_link" },
          { with_weight = 1, item = "jerky" },
          { with_weight = 1, item = "iodine_syringe" },
          { with_weight = 1, item = "stimpak" },
          { with_weight = 1, item = "fake_stimpak" },
          { with_weight = 1, item = "antidote" },
          { with_weight = 1, item = "blaster_bolt_device" },
          { with_weight = 1, item = "frag_grenade" },
          { with_weight = 1, item = "confusor" },
          { with_weight = 1, item = "tesla_coil" },
          { with_weight = 1, item = "rock" },
          { with_weight = 1, item = "baton" },
          { with_weight = 1, item = "knuckleduster" },
          { with_weight = 1, item = "pistol" },
          { with_weight = 1, item = "rifle" },
          { with_weight = 1, item = "leather_armor" },
          { with_weight = 1, item = "combat_armor" },
          { with_weight = 1, item = "flat_cap" },
          { with_weight = 1, item = "combat_helmet" },
          { with_weight = 1, item = "combat_boots" },
          { with_weight = 1, item = "navcomp" } ]

[4]
mapType = "Pillars"
being_probability = 0.003
item_probability = 0.01
beings = [ { with_weight = 2, being = "guard" },
           { with_weight = 2, being = "boxer" },
           { with_weight = 2, being = "mutant" },
           { with_weight = 1, being = "cyborg" },
           { with_weight = 2, being = "punk" } ]
items = [ { amount = 1, item = "phlebotinum_link" },
          { with_weight = 1, item = "jerky" },
          { with_weight = 1, item = "iodine_syringe" },
          { with_weight = 1, item = "stimpak" },
          { with_weight = 1, item = "fake_stimpak" },
          { with_weight = 1, item = "antidote" },
          { with_weight = 1, item = "blaster_bolt_device" },
          { with_weight = 1, item = "frag_grenade" },
          { with_weight = 1, item = "confusor" },
          { with_weight = 1, item = "tesla_coil" },
          { with_weight = 1, item = "rock" },
          { with_weight = 1, item = "baton" },
          { with_weight = 1, item = "knuckleduster" },
          { with_weight = 1, item = "pistol" },
          { with_weight = 1, item = "rifle" },
          { with_weight = 1, item = "leather_armor" },
          { with_weight = 1, item = "combat_armor" },
          { with_weight = 1, item = "flat_cap" },
          { with_weight = 1, item = "combat_helmet" },
          { with_weight = 1, item = "combat_boots" },
          { with_weight = 1, item = "navcomp" } ]

[5]
mapType = "Building"
being_probability = 0.003
item_probability = 0.01
beings = [ { with_weight = 2, being = "guard" },
           { with_weight = 2, being = "boxer" },
           { with_weight = 1, being = "mutant" },
           { with_weight = 1, being = "cyborg" },
           { with_weight = 1, being = "android" },
           { with_weight = 2, being = "punk" } ]
items = [ { amount = 1, item = "phlebotinum_link" },
          { with_weight = 1, item = "jerky" },
          { with_weight = 1, item = "iodine_syringe" },
          { with_weight = 1, item = "stimpak" },
          { with_weight = 1, item = "fake_stimpak" },
          { with_weight = 1, item = "antidote" },
          { with_weight = 1, item = "blaster_bolt_device" },
          { with_weight = 1, item = "frag_grenade" },
          { with_weight = 1, item = "confusor" },
          { with_weight = 1, item = "tesla_coil" },
          { with_weight = 1, item = "rock" },
          { with_weight = 1, item = "baton" },
          { with_weight = 1, item = "knuckleduster" },
          { with_weight = 1, item = "pistol" },
          { with_weight = 1, item = "rifle" },
          { with_weight = 1, item = "leather_armor" },
          { with_weight = 1, item = "combat_armor" },
          { with_weight = 1, item = "flat_cap" },
          { with_weight = 1, item = "combat_helmet" },
          { with_weight = 1, item = "combat_boots" },
          { with_weight = 1, item = "navcomp" } ]

[default]
mapType = "Building"
being_probability = 0.003
item_probability = 0.01
beings = [ { with_weight = 5, being = "dog" },
           { with_weight = 1, being = "snake" },
           { with_weight = 3, being = "child" },
           { with_weight = 1, being = "punk" } ]
items = [ { amount = 1, item = "phlebotinum_link" },
          { with_weight = 1, item = "jerky" },
          { with_weight = 1, item = "iodine_syringe" },
          { with_weight = 1, item = "stimpak" },
          { with_weight = 1, item = "fake_stimpak" },
          { with_weight = 1, item = "antidote" },
          { with_weight = 1, item = "blaster_bolt_device" },
          { with_weight = 1, item = "frag_grenade" },
          { with_weight = 1, item = "confusor" },
          { with_weight = 1, item = "tesla_coil" },
          { with_weight = 1, item = "rock" },
          { with_weight = 1, item = "baton" },
          { with_weight = 1, item = "knuckleduster" },
          { with_weight = 1, item = "pistol" },
          { with_weight = 1, item = "rifle" },
          { with_weight = 1, item = "leather_armor" },
          { with_weight = 1, item = "combat_armor" },
          { with_weight = 1, item = "flat_cap" },
          { with_weight = 1, item = "combat_helmet" },
          { with_weight = 1, item = "combat_boots" },
          { with_weight = 1, item = "navcomp" } ]
